### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [joshuadanpeterson/zsh-welcome-banner#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins). Could you please add a screen shot of what it displays on login? I like to only add entries to the list when users can see what they're getting without having to install a plugin.

Thanks!

**Comment by joshuadanpeterson** [comment]
Cool, thanks! Yes, I'll add it tonight and let you know.

**Comment by joshuadanpeterson** [comment]
@unixorn Screenshot added. Thanks again!
